### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by theomantz** [theomantz/mooboo#2]
Hey Vanessa,

I feel pretty good about the user authentication. Its styled fairly well and works so i think its ready for review. Thanks in advance!

**Comment by Vanchen07** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by Vanchen07** [comment]
-the logo wasn't loading which might just be an asset pipeline thing. Check out step 4 of the Heroku instructions: https://open.appacademy.io/learn/swe-in-person/full-stack-project/deploying-to-heroku
-just a couple things from the list above to add. Overall, very nice! Great job!

**Comment by theomantz** [comment]
Hi, Vanessa. Finally got back around to addressing the user auth issues and I think we're ready to check these off

**Comment by Vanchen07** [comment]
Looks good, thank you for the changes!
